### ISSUE TITLE
@import must precede all other statements (besides @charset)

### ISSUE THREAD

**Issue by thiagofelix** [basscss/addons#1]
When loading addons via postcss-importer it fails to load modules which have the @import statement located after other lines ( eg: border-colors ).

Example:
Project File

``` css
@import 'basscss';
@import 'basscss-btn';
@import 'basscss-btn-primary';
@import 'basscss-border-colors';

html {
  font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Helvetica,sans-serif
}
```

package.json

``` json
"dependencies": {
    "basscss": "^8.0.0-beta5",
    "basscss-border-colors": "^1.1.2",
    "basscss-btn": "^1.0.5",
    "basscss-btn-primary": "^1.0.2"
}
```

Error:

``` bash
WARNING in ./~/css-loader!./~/postcss-loader!./src/style/index.css
postcss-import: node_modules/basscss-border-colors/index.css:33:1: @import must precede all other statements (besides @charset)
```

Setup:
I am using webpack with postcss-loader + postcss-import plugin.

The root cause is from [postcss-import/parse-statement:83](https://github.com/postcss/postcss-import/blob/master/lib/parse-statements.js#L83)

Can we patch basscss/addons to have @imports always on the top while this constraint from postcss-import remains?

Thanks.
